import { expect, test } from "@playwright/test";

test("initial status discovery does not clear a selected file",async({page})=>{await page.route("**/api/v1/status",async route=>{const response=await route.fetch();await new Promise(resolve=>setTimeout(resolve,700));await route.fulfill({response})});await page.goto("/app");await page.getByLabel("Machine trajectory CSV").setInputFiles("e2e/fixtures/invalid.csv");const validate=page.getByRole("button",{name:"Validate trajectory"});await validate.focus();await page.keyboard.press("Enter");await expect(page.getByRole("alert")).toBeVisible();await expect(page.getByRole("button",{name:"New analysis"})).toBeVisible()});

test("reset rejects a late validation response",async({page})=>{await page.route("**/api/v1/datasets/inspect",async route=>{const response=await route.fetch();await new Promise(resolve=>setTimeout(resolve,700));await route.fulfill({response})});await page.goto("/app");await page.getByRole("button",{name:"Monitor sample"}).click();await page.getByRole("button",{name:"Validate trajectory"}).click();await page.getByRole("button",{name:"New analysis"}).click();await expect(page.getByText("Drop a machine trajectory here")).toBeVisible();await page.waitForTimeout(900);await expect(page.getByRole("heading",{name:"Choose a machine"})).toBeHidden()});

test("a second file invalidates an earlier successful result",async({page})=>{await page.goto("/app");await page.getByRole("button",{name:"Monitor sample"}).click();await page.getByRole("button",{name:"Validate trajectory"}).click();await page.getByRole("option").first().click();await page.getByRole("button",{name:"Estimate remaining life"}).click();await expect(page.locator("#prediction-result")).toBeVisible();await page.getByRole("button",{name:"Critical sample"}).click();await expect(page.locator("#prediction-result")).toBeHidden();await expect(page.getByRole("heading",{name:"Choose a machine"})).toBeHidden()});

test("rapid prediction submission produces one request",async({page})=>{let predictions=0;await page.route("**/api/v1/predictions",async route=>{predictions+=1;await route.continue()});await page.goto("/app");await page.getByRole("button",{name:"Monitor sample"}).click();await page.getByRole("button",{name:"Validate trajectory"}).click();await page.getByRole("option").first().click();const button=page.getByRole("button",{name:"Estimate remaining life"});await expect(button).toBeEnabled();await button.dblclick();await expect(page.locator("#prediction-result")).toBeVisible();expect(predictions).toBe(1)});
