export type MaintenanceStatus = "HEALTHY" | "MONITOR" | "PLAN_MAINTENANCE" | "CRITICAL";
export type SensorMap = Record<string, number>;
export interface SimulationSample { step:number; source_cycle:number; sensors:SensorMap; predicted_rul:number; lower_bound:number|null; upper_bound:number|null; maintenance_status:MaintenanceStatus; rul_change:number; important_features:string[]; warnings:string[]; model_version:string }
export interface SimulationAsset { asset_id:string; source_machine_id:number; display_name:string; samples:SimulationSample[] }
export interface SimulationEvent { id:string; cycle:number; asset_id:string; type:string; severity:"information"|"warning"|"critical"; message:string }
export interface ScenarioPack { schema_version:string; scenario_id:string; slug:string; title:string; description:string; simulation_only:true; simulation_label:string; simulation_warning:string; generated_at:string; source:{dataset_name:string;dataset_subset:string;dataset_fingerprint:string;attribution:string}; model:{name:string;version:string;rul_unit:string}; source_machine_ids:number[]; asset_manifest:Array<{asset_id:string;source_machine_id:number;display_name:string}>; timeline:{start:number;end:number;default_start:number;available_speeds:number[]}; sensor_definitions:Array<{id:string;label:string;unit:string}>; assets:SimulationAsset[]; events:SimulationEvent[]; checksum:string }
export interface Catalog { schema_version:string; simulation_only:true; simulation_warning:string; scenarios:Array<{scenario_id:string;slug:string;title:string;description:string;url:string;checksum:string;gzip_bytes:number}> }
export interface AssetSnapshot { asset:SimulationAsset; sample:SimulationSample; history:SimulationSample[]; alertCount:number }
export interface FleetSnapshot { scenario:ScenarioPack; step:number; playing:boolean; speed:number; assets:AssetSnapshot[]; events:SimulationEvent[]; statusCounts:Record<MaintenanceStatus,number>; medianRul:number; maintenanceDue:number; activeAlerts:number; complete:boolean }
export type WorkerCommand = {type:"LOAD";pack:ScenarioPack}|{type:"PLAY"}|{type:"PAUSE"}|{type:"STEP"}|{type:"RESET"}|{type:"SEEK";step:number}|{type:"SPEED";speed:number}|{type:"VISIBILITY";hidden:boolean}|{type:"SNAPSHOT"};
