import { lazy, Suspense, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Check, ChevronRight, CirclePause, CirclePlay, Command, Expand, RotateCcw, Search, SkipForward } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { useSimulation } from "../simulation/controller";
import { nextEvent } from "../simulation/events";
import { sortAssets } from "../simulation/selectors";
import type { AssetSnapshot, MaintenanceStatus, SimulationEvent } from "../simulation/contracts";
import { useSystemStatus } from "../api/queries";

const TelemetryChart=lazy(()=>import("../components/command/TelemetryChart"));
const statusLabel=(status:MaintenanceStatus)=>status.replace("PLAN_MAINTENANCE","PLAN MAINTENANCE");
const action=(asset:AssetSnapshot)=>asset.sample.maintenance_status==="CRITICAL"?"Immediate simulated review required":asset.sample.maintenance_status==="PLAN_MAINTENANCE"?"Inspect within the next simulated window":asset.sample.maintenance_status==="MONITOR"?"Increase observation frequency":"Continue monitoring";

function CompactHorizon({asset}:{asset:AssetSnapshot}){const value=asset.sample;const max=Math.max(125,value.upper_bound??0,value.predicted_rul);return <section className="cc-horizon" aria-label={`${asset.asset.asset_id} predicted remaining useful life ${value.predicted_rul} cycles, status ${statusLabel(value.maintenance_status)}`}><header><div><span className="tech-label">RUL HORIZON</span><strong>{value.predicted_rul.toFixed(1)} <small>cycles</small></strong></div><span className={`status status-${value.maintenance_status.toLowerCase()}`}>{statusLabel(value.maintenance_status)}</span></header><div className="cc-horizon-track"><span className="threshold critical" style={{left:`${25/max*100}%`}}/><span className="threshold warning" style={{left:`${50/max*100}%`}}/><i style={{width:`${Math.min(100,value.predicted_rul/max*100)}%`}}/>{value.lower_bound!=null&&value.upper_bound!=null&&<b style={{left:`${value.lower_bound/max*100}%`,width:`${(value.upper_bound-value.lower_bound)/max*100}%`}}/>}</div><footer><span>0</span><span>Range {value.lower_bound?.toFixed(1)??"—"}–{value.upper_bound?.toFixed(1)??"—"}</span><span>{max.toFixed(0)} cycles</span></footer></section>}

function FleetTile({item,selected,onSelect,pinned,onPin}:{item:AssetSnapshot;selected:boolean;onSelect:()=>void;pinned:boolean;onPin:()=>void}){const values=item.history.slice(-16).map(sample=>sample.sensors.sensor_11??0);const min=Math.min(...values),max=Math.max(...values),range=max-min||1;const points=values.map((value,index)=>`${index/(Math.max(1,values.length-1))*100},${26-(value-min)/range*22}`).join(" ");return <article className={`fleet-tile ${selected?"selected":""} edge-${item.sample.maintenance_status.toLowerCase()}`}><button className="fleet-main" onClick={onSelect} aria-pressed={selected}><header><strong>{item.asset.asset_id}</strong><span className={`status status-${item.sample.maintenance_status.toLowerCase()}`}>{statusLabel(item.sample.maintenance_status)}</span></header><div className="tile-metric"><b>{item.sample.predicted_rul.toFixed(1)}</b><small>cycles RUL</small><em>{item.sample.rul_change>0?"+":""}{item.sample.rul_change.toFixed(1)}</em></div><svg role="img" aria-label={`Recent sensor 11 trace for ${item.asset.asset_id}`} viewBox="0 0 100 28" preserveAspectRatio="none"><polyline points={points}/></svg><footer><span>C{item.sample.source_cycle}</span><span>{item.alertCount} alerts</span><span>fresh</span></footer></button><button className="pin" aria-pressed={pinned} onClick={onPin} aria-label={`${pinned?"Unpin":"Pin"} ${item.asset.asset_id}`}>⌖</button></article>}

export default function CommandCenterPage({maintenanceOnly=false}:{maintenanceOnly?:boolean}){const simulation=useSimulation();const status=useSystemStatus();const navigate=useNavigate();const params=useParams();const [selected,setSelected]=useState(params.assetId??"RT-01");const [filter,setFilter]=useState<"ALL"|MaintenanceStatus>("ALL");const [sort,setSort]=useState<"rul"|"decline"|"id">("rul");const [search,setSearch]=useState("");const [windowSize,setWindowSize]=useState(60);const [sensors,setSensors]=useState(["sensor_2","sensor_4","sensor_11"]);const [ack,setAck]=useState(new Set<string>());const [reviewed,setReviewed]=useState(new Set<string>());const [pins,setPins]=useState<string[]>([]);const [palette,setPalette]=useState(false);const [help,setHelp]=useState(false);const snap=simulation.snapshot;
  useEffect(()=>{const handler=(event:KeyboardEvent)=>{if(event.target instanceof HTMLInputElement||event.target instanceof HTMLSelectElement||event.target instanceof HTMLTextAreaElement)return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setPalette(true)}else if(event.key===" "){event.preventDefault();if(snap?.playing)simulation.pause();else simulation.play()}else if(event.key==="ArrowRight")simulation.step();else if(event.key==="1")simulation.setSpeed(1);else if(event.key==="5")simulation.setSpeed(5);else if(event.key==="0")simulation.setSpeed(20);else if(event.key.toLowerCase()==="f")document.getElementById("selected-asset")?.focus()};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)},[snap?.playing,simulation]);
  useEffect(()=>{setAck(new Set());setReviewed(new Set())},[snap?.scenario.scenario_id]);
  const selectedAsset=snap?.assets.find(item=>item.asset.asset_id===selected)??snap?.assets[0];const visible=useMemo(()=>snap?sortAssets(snap.assets.filter(item=>(filter==="ALL"||item.sample.maintenance_status===filter)&&item.asset.asset_id.toLowerCase().includes(search.toLowerCase())),sort):[],[snap,filter,search,sort]);const queue=useMemo(()=>snap?sortAssets(snap.assets.filter(item=>item.sample.maintenance_status!=="HEALTHY"),"rul"):[],[snap]);const events=snap?.events.slice().reverse()??[];
  if(simulation.error)return <div className="command-center telemetry-field"><div className="cc-error" role="alert"><AlertTriangle/><h1>Simulation unavailable</h1><p>{simulation.error}</p></div></div>;if(!snap)return <div className="command-center telemetry-field"><div className="cc-loading" role="status">Loading deterministic FD001 fleet…</div></div>;
  const choose=(id:string)=>{setSelected(id);if(params.assetId)navigate(`/asset/${id}`)};const jump=(severity?:string)=>{const event=nextEvent(snap.scenario.events,snap.step,severity);if(event){simulation.seek(event.cycle);setSelected(event.asset_id)}};
  return <div className="command-center telemetry-field"><header className="command-bar"><div className="fleet-identity"><span className="live-badge">LIVE SIMULATION</span><strong>FD001 Reliability Fleet</strong><small>No physical factory connection</small></div><div className="virtual-time"><span>VIRTUAL SHIFT</span><b>T+{String(snap.step).padStart(3,"0")}</b></div><label>Scenario<select value={snap.scenario.slug} onChange={event=>simulation.selectScenario(event.target.value)}>{simulation.catalog?.scenarios.map(item=><option value={item.slug} key={item.slug}>{item.title}</option>)}</select></label><div className="command-controls"><button onClick={snap.playing?simulation.pause:simulation.play} aria-label={snap.playing?"Pause simulation":"Play simulation"}>{snap.playing?<CirclePause/>:<CirclePlay/>}</button><button onClick={simulation.step} aria-label="Step one cycle"><SkipForward/></button><button onClick={simulation.reset} aria-label="Reset scenario"><RotateCcw/></button><select aria-label="Simulation speed" value={snap.speed} onChange={event=>simulation.setSpeed(Number(event.target.value))}>{[1,5,20].map(speed=><option value={speed} key={speed}>{speed}×</option>)}</select></div><button className="status-button" aria-label="API and model status"><i className={status.data?.data.prediction_available?"online":"offline"}/>{status.data?.data.model_state??"Checking model"}</button><button onClick={()=>document.documentElement.requestFullscreen?.()} aria-label="Enter full screen"><Expand/></button></header>
    <section className="kpi-strip" aria-label="Fleet key performance indicators">{[["Assets online",snap.assets.length],["Critical",snap.statusCounts.CRITICAL],["Maintenance due",snap.maintenanceDue],["Under watch",snap.statusCounts.MONITOR],["Median RUL",`${snap.medianRul} cyc`],["Active alerts",snap.activeAlerts-ack.size]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</section>
    {maintenanceOnly?<main className="maintenance-page"><header><div><span className="tech-label">MAINTENANCE CONTROL</span><h1>Priority queue</h1><p>Deterministic guidance from simulated RUL, status, and decline rate.</p></div><button className="cc-button" onClick={()=>navigate("/")}>Return to command center</button></header><MaintenanceQueue queue={queue} reviewed={reviewed} setReviewed={setReviewed} onFocus={id=>{setSelected(id);navigate(`/asset/${id}`)}} expanded/></main>:<main className="command-grid"><section className="fleet-panel"><div className="panel-title"><div><span className="tech-label">FLEET HEALTH MATRIX</span><h1>Rotating assets</h1></div><span>{visible.length}/{snap.assets.length}</span></div><div className="fleet-tools"><label><Search/><input aria-label="Search assets" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Asset ID"/></label><select aria-label="Filter fleet status" value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option>ALL</option>{["HEALTHY","MONITOR","PLAN_MAINTENANCE","CRITICAL"].map(value=><option key={value}>{value}</option>)}</select><select aria-label="Sort assets" value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="rul">Lowest RUL</option><option value="decline">Fastest decline</option><option value="id">Asset ID</option></select></div><div className="fleet-matrix">{visible.map(item=><FleetTile key={item.asset.asset_id} item={item} selected={item.asset.asset_id===selectedAsset?.asset.asset_id} onSelect={()=>choose(item.asset.asset_id)} pinned={pins.includes(item.asset.asset_id)} onPin={()=>setPins(current=>current.includes(item.asset.asset_id)?current.filter(id=>id!==item.asset.asset_id):current.length<3?[...current,item.asset.asset_id]:current)}/>)}</div></section>
      {selectedAsset&&<section className="asset-command" id="selected-asset" tabIndex={-1}><div className="asset-heading"><div><span className="tech-label">SELECTED ASSET COMMAND VIEW</span><h2>{selectedAsset.asset.display_name}</h2><p>Source machine {selectedAsset.asset.source_machine_id} · simulation cycle {snap.step} · FD001 cycle {selectedAsset.sample.source_cycle}</p></div><span className={`status large status-${selectedAsset.sample.maintenance_status.toLowerCase()}`}>{statusLabel(selectedAsset.sample.maintenance_status)}</span></div><CompactHorizon asset={selectedAsset}/><div className="asset-metrics"><span><small>10-cycle change</small><b>{(selectedAsset.sample.predicted_rul-(selectedAsset.history.at(-11)?.predicted_rul??selectedAsset.sample.predicted_rul)).toFixed(1)}</b></span><span><small>Current delta</small><b>{selectedAsset.sample.rul_change.toFixed(1)}</b></span><span><small>Warnings</small><b>{selectedAsset.sample.warnings.length}</b></span><span><small>Model</small><b>{selectedAsset.sample.model_version}</b></span></div><div className="sensor-controls"><span>Telemetry window</span>{[30,60,120].map(size=><button aria-pressed={windowSize===size} onClick={()=>setWindowSize(size)} key={size}>{size}</button>)}<span>Sensors</span>{snap.scenario.sensor_definitions.slice(0,8).map(sensor=><button aria-pressed={sensors.includes(sensor.id)} onClick={()=>setSensors(current=>current.includes(sensor.id)?current.filter(id=>id!==sensor.id):current.length<4?[...current,sensor.id]:current)} key={sensor.id}>{sensor.id.replace("sensor_","S")}</button>)}</div><Suspense fallback={<div className="chart-loading">Loading telemetry…</div>}><TelemetryChart samples={selectedAsset.history.slice(-windowSize)} sensors={sensors}/></Suspense><div className="asset-evidence"><article><span className="tech-label">IMPORTANT MODEL FEATURES</span>{selectedAsset.sample.important_features.map(feature=><code key={feature}>{feature}</code>)}</article><article><span className="tech-label">CURRENT WARNINGS</span>{selectedAsset.sample.warnings.length?selectedAsset.sample.warnings.map(warning=><p key={warning}>{warning}</p>):<p>No data-quality warning at this cycle.</p>}</article></div></section>}
      <aside className="operations-side"><section className="alert-feed"><div className="panel-title"><div><span className="tech-label">LIVE ALERT FEED</span><h2>Events</h2></div><button onClick={()=>jump("critical")}>Next critical</button></div>{events.length?events.slice(0,8).map(event=><AlertRow event={event} acknowledged={ack.has(event.id)} key={event.id} onAck={()=>setAck(current=>new Set(current).add(event.id))} onFocus={()=>{simulation.seek(event.cycle);choose(event.asset_id)}}/>):<p className="empty-copy">No threshold event has occurred.</p>}</section><MaintenanceQueue queue={queue.slice(0,6)} reviewed={reviewed} setReviewed={setReviewed} onFocus={choose}/></aside></main>}
    <footer className="time-conductor"><div><span className="tech-label">TIME CONDUCTOR</span><b>{snap.scenario.title}</b></div><button aria-label={snap.playing?"Pause simulation":"Play simulation"} onClick={snap.playing?simulation.pause:simulation.play}>{snap.playing?<CirclePause/>:<CirclePlay/>}</button><button aria-label="Step one cycle" onClick={simulation.step}><SkipForward/></button><input aria-label="Seek simulation cycle" type="range" min={snap.scenario.timeline.start} max={snap.scenario.timeline.end} value={snap.step} onChange={event=>simulation.seek(Number(event.target.value))}/><span>CYCLE {snap.step}/{snap.scenario.timeline.end}</span><button onClick={()=>jump("warning")}>Next warning <ChevronRight/></button><button onClick={()=>jump("critical")}>Next critical <ChevronRight/></button><button onClick={()=>setPalette(true)}><Command/> Commands</button><button aria-label="Open keyboard shortcuts" onClick={()=>setHelp(true)}>?</button></footer>
    {palette&&<div className="modal-backdrop" onMouseDown={()=>setPalette(false)}><section className="command-palette" role="dialog" aria-modal="true" aria-label="Command palette" onMouseDown={e=>e.stopPropagation()}><header><Command/><strong>Command palette</strong><kbd>Esc</kbd></header>{[["Pause or resume",snap.playing?simulation.pause:simulation.play],["Reset scenario",simulation.reset],["Open maintenance queue",()=>navigate("/maintenance")],["Open model evidence",()=>navigate("/model")],["Open Data Lab",()=>navigate("/lab")]].map(([label,run])=><button key={label as string} onClick={()=>{(run as ()=>void)();setPalette(false)}}>{label as string}<ChevronRight/></button>)}</section></div>}
    {help&&<div className="modal-backdrop" onMouseDown={()=>setHelp(false)}><section className="shortcuts" role="dialog" aria-modal="true" aria-labelledby="shortcuts-title" onMouseDown={e=>e.stopPropagation()}><h2 id="shortcuts-title">Keyboard controls</h2><dl><div><dt>Space</dt><dd>Play / pause</dd></div><div><dt>→</dt><dd>Step</dd></div><div><dt>1 / 5 / 0</dt><dd>Set speed</dd></div><div><dt>Ctrl / Cmd + K</dt><dd>Commands</dd></div><div><dt>F</dt><dd>Focus selected asset</dd></div></dl><button className="cc-button" onClick={()=>setHelp(false)}>Close</button></section></div>}
  </div>}

function AlertRow({event,acknowledged,onAck,onFocus}:{event:SimulationEvent;acknowledged:boolean;onAck:()=>void;onFocus:()=>void}){return <article className={`alert-row severity-${event.severity}`}><button className="alert-focus" onClick={onFocus}><span>{event.asset_id} · C{event.cycle}</span><strong>{event.message}</strong><small>{event.type.replaceAll("_"," ")}</small></button><button onClick={onAck} aria-label={`Acknowledge ${event.id}`} disabled={acknowledged}>{acknowledged?<Check/>:"Ack"}</button></article>}
function MaintenanceQueue({queue,reviewed,setReviewed,onFocus,expanded=false}:{queue:AssetSnapshot[];reviewed:Set<string>;setReviewed:(value:Set<string>)=>void;onFocus:(id:string)=>void;expanded?:boolean}){return <section className={`maintenance-queue ${expanded?"expanded":""}`}><div className="panel-title"><div><span className="tech-label">MAINTENANCE PRIORITY</span><h2>Queue</h2></div><span>{queue.length} due</span></div>{queue.map((item,index)=><article key={item.asset.asset_id}><b>{index+1}</b><button onClick={()=>onFocus(item.asset.asset_id)}><strong>{item.asset.asset_id}</strong><span>{item.sample.predicted_rul.toFixed(1)} cycles · {statusLabel(item.sample.maintenance_status)}</span><small>{action(item)}</small></button><button aria-label={`Mark ${item.asset.asset_id} reviewed`} className={reviewed.has(item.asset.asset_id)?"reviewed":""} onClick={()=>setReviewed(new Set(reviewed).add(item.asset.asset_id))}>{reviewed.has(item.asset.asset_id)?<Check/>:"Review"}</button></article>)}</section>}
