import React, { useEffect, useMemo, useRef, useState } from "react";
import { CirclePause, CirclePlay, ExternalLink, RotateCcw, Trash2 } from "lucide-react";
import { Link } from "react-router-dom";
import { usePins } from "../comparison/pins";
import { buildComparedAssets, comparisonDecision, sharedRulMaximum } from "../comparison/selectors";
import { useSimulation } from "../simulation/controller";

const colors = ["#68C8B8", "#75A8D7", "#D0A462"];
const statusLabel = (value:string) => value.replace("PLAN_MAINTENANCE", "PLAN MAINTENANCE");
const points = (values:number[], width:number, height:number, max:number) => values.map((value,index)=>`${index/Math.max(1,values.length-1)*width},${height-value/max*height}`).join(" ");

export default function ComparePage() {
  const simulation = useSimulation();
  const { pins, unpin, clear, retainValid } = usePins();
  const [windowSize,setWindowSize] = useState(60);
  const [sensor,setSensor] = useState("");
  const heading = useRef<HTMLHeadingElement>(null);
  const snap = simulation.snapshot;
  useEffect(()=>heading.current?.focus(),[]);
  useEffect(()=>{if(snap)retainValid(snap.scenario.asset_manifest.map(item=>item.asset_id))},[snap, retainValid]);
  useEffect(()=>{if(snap&&!snap.scenario.sensor_definitions.some(item=>item.id===sensor))setSensor(snap.scenario.sensor_definitions[0]?.id??"")},[snap,sensor]);
  const items=useMemo(()=>snap?buildComparedAssets(snap.assets,snap.events,pins):[],[snap,pins]);
  const decision=useMemo(()=>items.length?comparisonDecision(items):null,[items]);
  if(simulation.error)return <div className="cc-error" role="alert"><h1>Comparison unavailable</h1><p>{simulation.error}</p></div>;
  if(!snap)return <div className="cc-loading" role="status">Loading comparison…</div>;
  const rulMax=sharedRulMaximum(items);
  const sensorDefinition=snap.scenario.sensor_definitions.find(item=>item.id===sensor);
  const sensorValues=items.flatMap(item=>item.history.slice(-windowSize).map(sample=>sample.sensors[sensor]).filter((value):value is number=>value!=null));
  const sensorMin=Math.min(...sensorValues,0), sensorMax=Math.max(...sensorValues,1), sensorRange=sensorMax-sensorMin||1;
  return <div className="compare-page telemetry-field"><header className="compare-header"><div><span className="tech-label">PINNED ASSET COMPARISON</span><h1 ref={heading} tabIndex={-1}>Operational comparison</h1><p>Shared scales at scenario cycle {snap.step}. Values update with the deterministic simulation snapshot.</p></div><div className="compare-actions"><Link className="cc-button" to="/command">Return to fleet</Link><button className="cc-button" onClick={clear} disabled={!pins.length}>Clear all pins</button></div></header>
    <div className="compare-conductor"><label>Scenario<select value={snap.scenario.slug} onChange={event=>simulation.selectScenario(event.target.value)}>{simulation.catalog?.scenarios.map(item=><option key={item.slug} value={item.slug}>{item.title}</option>)}</select></label><button onClick={snap.playing?simulation.pause:simulation.play} aria-label={snap.playing?"Pause simulation":"Play simulation"}>{snap.playing?<CirclePause/>:<CirclePlay/>}</button><button onClick={simulation.reset} aria-label="Reset scenario"><RotateCcw/></button><label>Cycle <input aria-label="Seek comparison cycle" type="range" min={snap.scenario.timeline.start} max={snap.scenario.timeline.end} value={snap.step} onChange={event=>simulation.seek(Number(event.target.value))}/></label><span>{snap.step}/{snap.scenario.timeline.end}</span></div>
    {!items.length?<section className="compare-empty"><h2>No pinned assets</h2><p>Pin one to three assets in the Fleet Health Matrix or maintenance queue to start a shared-axis comparison.</p><Link className="button primary" to="/">Open Fleet Health Matrix</Link></section>:<main className="compare-content">
      <section className="decision-summary" aria-labelledby="decision-title"><div><span className="tech-label">DECISION SUMMARY</span><h2 id="decision-title">Review {decision!.highestPriority.asset.asset_id} first</h2><p>Deterministic order: {decision!.reviewOrder.map(item=>item.asset.asset_id).join(" → ")}</p></div><dl><div><dt>Lowest RUL</dt><dd>{decision!.lowest.asset.asset_id} · {decision!.lowest.sample.predicted_rul.toFixed(1)}</dd></div><div><dt>Fastest decline</dt><dd>{decision!.fastest.asset.asset_id} · {decision!.fastest.declineRate.toFixed(2)}/cycle</dd></div><div><dt>Most critical alert state</dt><dd>{decision!.alert.asset.asset_id} · {decision!.alert.events.at(-1)?.severity??"none"}</dd></div></dl></section>
      <section className="comparison-overview" aria-label="Pinned asset current snapshot">{items.map((item,index)=><article key={item.asset.asset_id} style={{"--asset-color":colors[index]} as React.CSSProperties}><header><div><span className="asset-key" aria-hidden="true">{index+1}</span><h2>{item.asset.asset_id}</h2></div><button onClick={()=>unpin(item.asset.asset_id)} aria-label={`Remove ${item.asset.asset_id} from comparison`}><Trash2/></button></header><span className={`status status-${item.sample.maintenance_status.toLowerCase()}`}>{statusLabel(item.sample.maintenance_status)}</span><strong>{item.sample.predicted_rul.toFixed(1)} <small>cycles RUL</small></strong><dl><div><dt>Current cycle</dt><dd>{item.sample.source_cycle}</dd></div><div><dt>Prediction range</dt><dd>{item.sample.lower_bound?.toFixed(1)??"missing"}–{item.sample.upper_bound?.toFixed(1)??"missing"}</dd></div><div><dt>RUL delta</dt><dd>{item.sample.rul_change.toFixed(1)}</dd></div><div><dt>Decline rate</dt><dd>{item.declineRate.toFixed(2)}/cycle</dd></div><div><dt>Active alerts</dt><dd>{item.events.length}</dd></div><div><dt>Data freshness</dt><dd>cycle {snap.step-item.sample.step === 0?"current":snap.step-item.sample.step}</dd></div><div><dt>Top feature</dt><dd>{item.sample.important_features[0]??"not available"}</dd></div><div><dt>Warnings</dt><dd>{item.sample.warnings.length}</dd></div></dl><Link to={`/asset/${item.asset.asset_id}`}>Investigate asset <ExternalLink/></Link></article>)}</section>
      <section className="compare-panel"><header><div><span className="tech-label">SHARED RUL SCALE</span><h2>Remaining useful life and prediction range</h2></div><span>0–{rulMax.toFixed(0)} cycles</span></header><p className="sr-only">RUL chart summary. {items.map(item=>`${item.asset.asset_id}: ${item.sample.predicted_rul.toFixed(1)} cycles, range ${item.sample.lower_bound?.toFixed(1)??"missing"} to ${item.sample.upper_bound?.toFixed(1)??"missing"}, status ${statusLabel(item.sample.maintenance_status)}.`).join(" ")}</p><div className="rul-shared-chart">{items.map((item,index)=><div className="rul-shared-row" key={item.asset.asset_id}><b><i style={{background:colors[index]}}/>{item.asset.asset_id}</b><div><span className="threshold critical" style={{left:`${25/rulMax*100}%`}}/><span className="threshold warning" style={{left:`${50/rulMax*100}%`}}/>{item.sample.lower_bound!=null&&item.sample.upper_bound!=null&&<i className="range" style={{left:`${item.sample.lower_bound/rulMax*100}%`,width:`${(item.sample.upper_bound-item.sample.lower_bound)/rulMax*100}%`}}/>}<i className="value" style={{left:`${item.sample.predicted_rul/rulMax*100}%`,background:colors[index]}}/></div><span>{item.sample.predicted_rul.toFixed(1)}</span></div>)}</div></section>
      <section className="compare-panel"><header><div><span className="tech-label">RUL TREND</span><h2>Recent unsmoothed prediction history</h2></div><WindowControl value={windowSize} onChange={setWindowSize}/></header><p className="sr-only">Shared cycle and RUL axes. {items.map(item=>`${item.asset.asset_id} changed from ${item.history.slice(-windowSize)[0]?.predicted_rul.toFixed(1)} to ${item.sample.predicted_rul.toFixed(1)} cycles.`).join(" ")}</p><svg className="compare-line-chart" role="img" aria-label="Pinned asset RUL trends on shared cycle and RUL axes" viewBox="0 0 800 220" preserveAspectRatio="none">{items.map((item,index)=><polyline key={item.asset.asset_id} points={points(item.history.slice(-windowSize).map(sample=>sample.predicted_rul),800,210,rulMax)} stroke={colors[index]}/>)}</svg><Legend items={items.map((item,index)=>[item.asset.asset_id,colors[index]])}/></section>
      <section className="compare-panel"><header><div><span className="tech-label">SENSOR COMPARISON</span><h2>{sensorDefinition?.label??sensor} {sensorDefinition?.unit&&`(${sensorDefinition.unit})`}</h2></div><label>Selected sensor<select aria-label="Selected comparison sensor" value={sensor} onChange={event=>setSensor(event.target.value)}>{snap.scenario.sensor_definitions.map(item=><option key={item.id} value={item.id}>{item.label} · {item.unit}</option>)}</select></label></header><p className="sr-only">Sensor chart summary. {items.map(item=>{const values=item.history.slice(-windowSize).map(sample=>sample.sensors[sensor]).filter((value):value is number=>value!=null);return `${item.asset.asset_id}: current ${values.at(-1)?.toFixed(2)??"missing"}; ${values.length?"data available":"missing data"}.`}).join(" ")}</p><svg className="compare-line-chart" role="img" aria-label={`${sensorDefinition?.label??sensor} comparison on a shared ${sensorDefinition?.unit??"unit"} scale`} viewBox="0 0 800 220" preserveAspectRatio="none">{items.map((item,index)=>{const values=item.history.slice(-windowSize).map(sample=>sample.sensors[sensor]);if(values.every(value=>value==null))return null;return <polyline key={item.asset.asset_id} points={points(values.map(value=>(value??sensorMin)-sensorMin),800,210,sensorRange)} stroke={colors[index]}/>})}</svg><div className="sensor-current">{items.map(item=><span key={item.asset.asset_id}><b>{item.asset.asset_id}</b> {item.sample.sensors[sensor]?.toFixed(2)??"Missing data"}</span>)}</div><Legend items={items.map((item,index)=>[item.asset.asset_id,colors[index]])}/></section>
      <section className="sensor-deviations" aria-label="Latest sensor deviations"><span className="tech-label">LATEST DEVIATION</span>{items.map(item=>{const deviation=item.events.filter(event=>event.type==="SENSOR_DEVIATION").at(-1);return <p key={item.asset.asset_id}><b>{item.asset.asset_id}</b>: {deviation?`${deviation.message} at cycle ${deviation.cycle}`:"No sensor deviation event in the current snapshot."}</p>})}</section>
    </main>}
  </div>
}
function WindowControl({value,onChange}:{value:number;onChange:(value:number)=>void}){return <div className="compare-window" aria-label="Telemetry window">{[30,60,120].map(size=><button key={size} aria-pressed={value===size} onClick={()=>onChange(size)}>{size} cycles</button>)}</div>}
function Legend({items}:{items:string[][]}){return <div className="compare-legend" aria-label="Asset legend">{items.map(([label,color])=><span key={label}><i style={{background:color}}/>{label}</span>)}</div>}
