import { ArrowRight, Database, FileCheck2, Gauge, Layers3, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { useState } from "react";
import { useEvaluation, useMetadata, useSystemStatus } from "../api/queries";
import { predictMachine } from "../api/mutations";
import type { PredictionData } from "../api/types";
import { SensorLattice } from "../components/layout/SensorLattice";
import { MetricTile } from "../components/primitives/MetricTile";
import { RULHorizon } from "../components/prediction/RULHorizon";
import { SystemStateChip } from "../components/status/SystemStateChip";

async function demoFile() { const response = await fetch("/samples/demo_machine_monitor.csv"); const blob = await response.blob(); return new File([blob], "demo_machine_monitor.csv", { type: "text/csv" }); }

export default function LandingPage() {
  const metadata = useMetadata(), evaluation = useEvaluation(), status = useSystemStatus();
  const [preview, setPreview] = useState<PredictionData>(); const [loading, setLoading] = useState(false); const [previewError, setPreviewError] = useState(false);
  const final = evaluation.data?.data.final_test;
  const runPreview = async () => { setLoading(true); setPreviewError(false); try { const file = await demoFile(); setPreview((await predictMachine(file, "9001")).data); } catch { setPreviewError(true); } finally { setLoading(false); } };
  return <>
    <section className="hero"><SensorLattice /><div className="hero-copy"><div className="hero-kicker"><SystemStateChip status={status.data?.data} unavailable={status.isError} /><span>FD001 remaining useful life</span></div><h1>Know how long a machine has left—<em>before downtime chooses for you.</em></h1><p>Analyze historical sensor trajectories and estimate remaining useful life in cycles with the real FD001-trained model. Predictions are evidence-based estimates, not guarantees.</p><div className="hero-actions"><Link className="button primary" to="/app">Analyze a machine <ArrowRight /></Link><Link className="button secondary" to="/app/model">Inspect model evidence</Link></div></div>
      <div className="hero-visual"><div className="telemetry-cap"><span>Signal Foundry</span><code>{metadata.data?.data.model_name ?? "model pending"} / {metadata.data?.data.model_version ?? "—"}</code></div><RULHorizon prediction={preview} thresholds={metadata.data?.data.maintenance_thresholds} compact /><button className="preview-trigger" type="button" disabled={loading || status.data?.data.demo_only !== true} onClick={runPreview}>{loading ? <><span className="spinner" /> Running demo analysis</> : preview ? "Run sample again" : "Run the real demo workflow"}</button>{previewError && <p className="inline-warning">Demo preview is unavailable. Open the workspace to upload a file.</p>}</div>
    </section>
    <section className="evidence-strip" aria-label="Official model evidence"><MetricTile label="Official FD001 test machines" value={final ? String(final.machine_count) : "—"} detail="held-out trajectories" variant="information" /><MetricTile label="Mean absolute error" value={final ? `${final.mae.toFixed(2)} cycles` : "Unavailable"} detail="official test split" variant="healthy" /><MetricTile label="Near-failure MAE" value={final?.near_failure_mae != null ? `${final.near_failure_mae.toFixed(2)} cycles` : "Unavailable"} detail="0–25 RUL band" variant="warning" /></section>
    <section className="content-section process"><div className="section-intro"><span className="eyebrow">One disciplined workflow</span><h2>From trajectory to maintenance evidence</h2><p>The browser retains your file only for the current analysis and resends it to the stateless API when needed.</p></div><div className="process-grid">{[[FileCheck2,"01","Upload trajectory","Choose an FD001-shaped CSV or a clearly marked synthetic demo sample."],[ShieldCheck,"02","Validate sensor history","Confirm schema, machine cycles, and sufficient observations before inference."],[Gauge,"03","Estimate remaining life","The backend model returns RUL, range, status, and model evidence."],[Layers3,"04","Review maintenance evidence","Inspect sensor history, important features, warnings, and limitations."]].map(([Icon,n,title,copy]) => { const C = Icon as typeof FileCheck2; return <article key={String(n)}><span>{String(n)}</span><C /><h3>{String(title)}</h3><p>{String(copy)}</p></article>; })}</div></section>
    <section className="content-section preview-section"><div className="section-intro"><span className="eyebrow">Product preview</span><h2>A prediction surface built around the decision</h2></div><div className="preview-frame"><div className="preview-sidebar"><Database /><span>Trajectory</span><strong>{preview ? `M-${preview.machine_id}` : "No machine selected"}</strong><small>{preview ? `Observed through ${preview.observed_through_cycle}` : "Run the demo workflow above"}</small></div><RULHorizon prediction={preview} thresholds={metadata.data?.data.maintenance_thresholds} /></div></section>
    <section className="content-section trust"><div className="section-intro"><span className="eyebrow">Model transparency</span><h2>Useful evidence, honestly bounded</h2></div><div className="trust-grid"><article><h3>Dataset</h3><p>NASA C-MAPSS FD001, a single operating-condition and fault-mode benchmark. Official evaluation uses 100 held-out test machines.</p></article><article><h3>Model</h3><p>{metadata.data ? `${metadata.data.data.model_name} version ${metadata.data.data.model_version}, trained on real FD001 trajectories.` : "Model identity is supplied by API metadata."}</p></article><article><h3>Target and range</h3><p>RUL is measured in cycles and capped at 125 during training. Prediction ranges come from validation residual quantiles—not certainty.</p></article><article><h3>Limitations</h3><p>FD001 is a benchmark, not every factory. Operational decisions require qualified engineering review and site-specific validation.</p></article></div></section>
    <section className="final-cta"><span className="eyebrow">Signal to decision</span><h2>Bring a machine trajectory into focus.</h2><Link className="button primary" to="/app">Open analysis workspace <ArrowRight /></Link></section>
    <footer><span>LiveOps AI</span><Link to="/app">Product</Link><button type="button" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}>API status</button><a href="https://www.nasa.gov/content/prognostics-center-of-excellence-data-set-repository" rel="noreferrer">NASA C-MAPSS attribution</a></footer>
  </>;
}
