import { useEvaluation, useMetadata, useSystemStatus } from "../api/queries";
import { MetricTile } from "../components/primitives/MetricTile";
import { FocusLensCard } from "../components/primitives/FocusLensCard";
import { ErrorState } from "../components/status/ErrorState";

export default function ModelEvidencePage() {
  const metadata = useMetadata(), evaluation = useEvaluation(), status = useSystemStatus();
  if (metadata.isError || evaluation.isError) return <div className="evidence-page"><ErrorState error={metadata.error ?? evaluation.error} /></div>;
  const meta = metadata.data?.data, data = evaluation.data?.data, final = data?.final_test; const models = data?.validation_models ?? []; const maxMae = Math.max(...models.map((item) => item.mae), 1);
  return <div className="evidence-page"><header className="evidence-hero"><span className="eyebrow">Model evidence</span><h1>Traceable performance,<br />without the theatre.</h1><p>LiveOps AI uses an Extra Trees regression pipeline—not deep learning—trained on machine-disjoint FD001 trajectories and evaluated on the official test split.</p><div className="evidence-identity"><code>{meta?.model_name ?? "Loading"}</code><span>version {meta?.model_version ?? "—"}</span><span>{meta?.training_data_kind ?? "—"} training data</span></div></header>
    <section className="content-section"><div className="section-intro"><span className="eyebrow">Official evaluation</span><h2>Held-out FD001 results</h2></div><div className="metric-grid"><MetricTile label="Test machines" value={final ? String(final.machine_count) : "Unavailable"} variant="information" /><MetricTile label="MAE" value={final ? `${final.mae.toFixed(2)} cycles` : "Unavailable"} variant="healthy" /><MetricTile label="RMSE" value={final ? `${final.rmse.toFixed(2)} cycles` : "Unavailable"} /><MetricTile label="Median absolute error" value={final ? `${final.median_absolute_error.toFixed(2)} cycles` : "Unavailable"} /><MetricTile label="R²" value={final ? final.r2.toFixed(3) : "Unavailable"} /><MetricTile label="Near-failure MAE" value={final?.near_failure_mae != null ? `${final.near_failure_mae.toFixed(2)} cycles` : "Unavailable"} variant="warning" /></div></section>
    <section className="content-section comparison"><div className="section-intro"><span className="eyebrow">Baseline comparison</span><h2>Candidate model validation</h2><p>Lower MAE is better. Model selection considered error, near-failure behavior, stability, runtime, and size.</p></div><FocusLensCard className="comparison-card">{models.map((model) => <div className="comparison-row" key={model.model_name}><div><strong>{model.model_name.replaceAll("_", " ")}</strong><span>{model.near_failure_mae != null ? `Near-failure ${model.near_failure_mae.toFixed(2)}` : "Near-failure unavailable"}</span></div><div className="comparison-track"><span style={{ width: `${(model.mae / maxMae) * 100}%` }} /></div><code>{model.mae.toFixed(2)} MAE</code></div>)}</FocusLensCard></section>
    <section className="content-section error-bands"><div className="section-intro"><span className="eyebrow">Error by RUL band</span><h2>Performance changes across the horizon</h2></div><div className="band-grid">{final ? Object.entries(final.error_by_rul_band).map(([band, value]) => <article key={band}><span>{band} cycles</span><strong>{value.toFixed(2)}</strong><small>mean absolute error</small><div><i style={{ height: `${Math.min(100, value * 4)}%` }} /></div></article>) : <p>No official error bands are available.</p>}</div></section>
    <section className="content-section pipeline"><div className="section-intro"><span className="eyebrow">Model pipeline</span><h2>Causal features, explicit boundaries</h2></div><div className="pipeline-diagram"><span>FD001 trajectories</span><i>→</i><span>Current + trailing features</span><i>→</i><span>Extra Trees regression</span><i>→</i><span>RUL + residual range</span></div></section>
    <section className="content-section trust model-details"><article><h3>Target construction</h3><p>The backend constructs capped RUL as cycles remaining to failure, with a cap of 125. The frontend never reproduces this logic.</p></article><article><h3>Feature methodology</h3><p>Current measurements, trailing mean, trailing standard deviation, and previous-cycle delta use only present and past observations.</p></article><article><h3>Dataset provenance</h3><p>NASA C-MAPSS FD001 represents one operating condition and one fault mode. Official evaluation contains 100 test machines.</p></article><article><h3>Limitations</h3><p>Benchmark accuracy does not prove transfer to every asset or factory. Maintenance decisions require qualified review.</p></article></section>
    <section className="version-table"><h2>API and model versions</h2><dl><div><dt>API</dt><dd>{status.data?.data.api_version ?? "—"}</dd></div><div><dt>Backend contract</dt><dd>{status.data?.data.backend_contract_version ?? "—"}</dd></div><div><dt>Model</dt><dd>{meta?.model_version ?? "—"}</dd></div><div><dt>Artifact</dt><dd>{meta?.artifact_version ?? "—"}</dd></div></dl></section>
  </div>;
}
